spring.application.name=pricing-service
server.port=${pricing-service.uriport}

spring.cloud.config.profile=dev
spring.config.import=optional:configserver:http://localhost:8888

spring.datasource.url=${pricing-service.datasource-url}
spring.jpa.defer-datasource-initialization=true
spring.datasource.username=${pricing-service.username}
spring.datasource.password=${pricing-service.password}

spring.jpa.hibernate.ddl-auto=${pricing-service.hibernate-ddl-auto}
spring.jpa.show-sql=${pricing-service.showsql}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

eureka.client.service-url.defaultZone: ${pricing-service.urlregistry}

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
